In [1]:
import numpy as np

In [2]:
A= np.array([[5, 1, -2, 0], [0, 3, 4, 3], [2, 3, 1, 1]])

In [3]:
B = np.array([[1, -3], [2, -2], [3, -1], [0, 0]])

In [4]:
np.dot(A, B).shape

(3, 2)

**Перемножение матриц**

Напишите две функции, каждая из которых перемножает две квадратные матрицы: одна без использования встроенных функций numpy, а другая --- с помощью numpy. На вход обеим задачам подаются объекты типа np.ndarray --- квадратные матрицы одинакового размера. 

Первая функция должна возвращать список списков, а вторая -- np.array.

In [5]:
def no_numpy_mult(first, second):
    """
    param first: list of "size" lists, each contains "size" floats
    param first: list of "size" lists, each contains "size" floats
    """
    rows_first = len(first)
    cols_first = len(first[0])
    rows_second = len(second)
    cols_second = len(second[0])
    
    if cols_first != rows_second:
        return []
    
    a = [[0 for row in range(cols_second)] for col in range(rows_first)]

    for i in range(rows_first):
        for j in range(cols_second):
            for k in range(cols_first):
                a[i][j] += first[i][k]*second[k][j]
    result = a 
    return result

def numpy_mult(first, second):
    """
    param first: np.array[size, size]
    param second: np.array[size, size]
    """
    result = np.dot(first, second)
    return result

A = [[1, 2], [3, 5]]
B = [[1, 2], [3, 5]]
print(no_numpy_mult(A, B))

A = np.array([[1, 2], [3, 5]])
B = np.array([[1, 2], [3, 5]])
print(numpy_mult(A, B))

[[7, 12], [18, 31]]
[[ 7 12]
 [18 31]]


**Скалярное произведение**

Вам подаются на вход два вектора a и b в трехмерном пространстве. Реализуйте их скалярное произведение с помощью numpy и без. 

In [6]:
def no_numpy_scalar(v1, v2):
    if len(v1) == len(v2):
        result = sum([v1[i]*v2[i] for i in range(len(v1))])
        return result
    return

def numpy_scalar(v1, v2):
    result = np.dot(v1, v2)
    return result

A = [1, 2, 3, 5]
B = [1, 2, 3, 5]
print(no_numpy_scalar(A, B))

A = np.array([1, 2, 3, 5])
B = np.array([1, 2, 3, 5])
print(numpy_scalar(A, B))

39
39


Напишите функцию, которая находим сумму четных диагональных элементов квадратной матрицы (именно чётных элементов, а не элементов на чётных позициях!). Если чётных элементов нет, то вывести 0. Используйте библиотеку numpy.

In [7]:
def diag_2k(a):
    summa = 0
    d = np.diag(a)
    
    for item in d:
        if item % 2 == 0:
            summa += item
    
    result = summa
    return result

A = [[1, 7, 6], [5, 1, 8], [1, 3, 1]]
print(diag_2k(A))

0


На вход дан двумерный массив X. Напишите функцию, которая для каждой строчки x=(x1,x2,…,xn) массива X строит строчку s=(s1,s2,…,sn), где sk=x1+...+xk, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и X.

In [8]:
def cumsum(A):
    result = np.zeros_like(A)
    for i in range(len(A)):
        result[i, :] = np.cumsum(A[i])
    return result

A = [[1, 7, 6], [5, 1, 8], [1, 3, 1]]
print(cumsum(A))

[[ 1  8 14]
 [ 5  6 14]
 [ 1  4  5]]


С помощью numpy написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [9]:
def encode(a):
    ia = np.asarray(a)
    n = len(ia)
    if n == 0: 
        return (None, None)
    else:
        y = np.array(ia[1:] != ia[:-1])
        i = np.append(np.where(y), n - 1)
        z = np.diff(np.append(-1, i))
        return(ia[i], z)

A = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
print(encode(A))

(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2], dtype=int64))


**Склеивание**

Задан одномерный массив X. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив X с преобразованным X и вернуть на выход.

Напишите функцию, которая выполняет данное преобразование. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
x = [100,200,300,400,500] -> [100,a,300,a,500] -> [5003,a,3003,a,1003] -> склеиваем -> [100,200,300,400,500,5003,a,3003,a,1003]

In [10]:
import copy

def transform(X, a=1):
    """
    param X: np.array
    """
    result = []
    
    if len(X.shape) == 1:
        X = np.expand_dims(X, axis=0)
    
    for idx, arr in enumerate(X):
        Y = copy.deepcopy(arr)
        Y[1::2] = a
        Y[::2] = arr[::2]**3
        Y = Y[::-1]
        result.append(np.hstack((arr,Y)))
    
    return result

x = np.array([100,200,300,400,500])
print(transform(x, 1))
# Вывод:
# [      100       200       300       400       500 125000000         1
#  27000000         1   1000000]

x = np.array([[100,200,300,400,500], [1, 2, 4, 5, 6]])
print(transform(x, 1))
# Вывод:
# [[      100       200       300       400       500 125000000         1
#   27000000         1   1000000]
# [        1         2         4         5         6       216         1
#         64         1         1]]

[array([      100,       200,       300,       400,       500, 125000000,
               1,  27000000,         1,   1000000])]
[array([      100,       200,       300,       400,       500, 125000000,
               1,  27000000,         1,   1000000]), array([  1,   2,   4,   5,   6, 216,   1,  64,   1,   1])]
